"行番号表示
set number

syntax enable

" 検索するときに大文字小文字を区別しない
set ignorecase

" ファイルを上書きする前にバックアップを作ることを無効化
set nowritebackup

" ファイルを上書きする前にバックアップを作ることを無効化
set nobackup

"set default shell
set shell=bash

" スワップファイルを作成しない
set noswapfile

set autoindent 

set tabstop=4
set shiftwidth=4

inoremap { {}<LEFT>
inoremap [ []<LEFT>
inoremap ( ()<LEFT>
inoremap " ""<LEFT>
inoremap ' ''<LEFT>
" jjをEscキーとして扱う
inoremap jj <Esc>
cnoremap jj <Esc>
" vnoremap jj <Esc>
nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>

"Get the 2-space YAML as the default when hit carriage return after the colon
"autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab"
"
source ./fudebako.vim/manager.vim
